### ISSUE TITLE
java api; getExecutionState NullPointerException whhen parsing XML response

### ISSUE THREAD

**Issue by insee-ab** [rundeck/rundeck-api-java-client#20]
Hi
We use
- Rundeck 2.3.2
- API java: 	<artifactId>rundeck-api-java-client</artifactId><version>12.0</version>
We create a RundeckClient with version 12 then execute a job.

When we use the method getExecutionState we have a NullPointerException when the rundeck-api-java-client parses the Xml response which contents at the top level a "result" element

``` {.xml}
<result success='true' apiversion='12'><executionState id='27'><executionId>27</executionId><serverNode>W100024302</serverNode><executionState>SUCCEEDED</executionState><completed>true</completed><targetNodes><nodes><node name='W100024302'></node></nodes></targetNodes><allNodes><nodes><node name='W100024302'></node></nodes></allNodes><stepCount>1</stepCount><updateTime>2015-02-26T16:14:29Z</updateTime><startTime>2015-02-26T16:14:28Z</startTime><endTime>2015-02-26T16:14:29Z</endTime><steps><step stepctx='1' id='1'><parameterStates></parameterStates><nodeStep>true</nodeStep><executionState>SUCCEEDED</executionState><startTime>2015-02-26T16:14:28Z</startTime><updateTime>2015-02-26T16:14:28Z</updateTime><endTime>2015-02-26T16:14:29Z</endTime><nodeStates><nodeState name='W100024302'><executionState>SUCCEEDED</executionState><startTime>2015-02-26T16:14:29Z</startTime><updateTime>2015-02-26T16:14:29Z</updateTime><endTime>2015-02-26T16:14:29Z</endTime></nodeState></nodeStates></step></steps><nodes><node name='W100024302'><steps><step><stepctx>1</stepctx><executionState>SUCCEEDED</executionState></step></steps></node></nodes></executionState></result>
```

The StrackTrace:

```
Exception in thread "main" java.lang.NullPointerException
	at org.rundeck.api.parser.ExecutionStateParser.parseXmlNode(ExecutionStateParser.java:33)
	at org.rundeck.api.parser.ExecutionStateParser.parseXmlNode(ExecutionStateParser.java:14)
```

When we explore the error, it seems that the rundeck-api-java-client uses a rootelement "" (rootXpath() returns "")  and so the parsed node is null, then NullPointeException

When we create a RundeckClient with version 10 (rootXpath() returns "result"), all is OK, no Exception.

A bug in rundeck-api-java-client ?

Thanks !

**Comment by gschueler** [comment]
Sounds like this fix wasn't complete: https://github.com/rundeck/rundeck-api-java-client/pull/17/commits

workaround would be to stick with client version 10, or update to rundeck 2.4

**Comment by gschueler** [comment]
fyi: http://rundeck.org/docs/history/version-2.4.0.html#compatibility-notes
