### ISSUE TITLE
Client can't connect to internal server when behind proxy

### ISSUE THREAD

**Issue by andham** [rundeck/rundeck-api-java-client#22]
I'm in a corporate network where we use a web proxy to access the Internet. Our rundeck server is internal though, and connection shouldn't be via the proxy.

When trying to connect to the server, this doesn't work. I've found it's the client code setting
`System.setProperty("java.net.useSystemProxies", "true");`
that "causes" this. If I remove this in the ApiCall class, it works.

I'm specifying the full server name. I guess that there could be something wrong in the system proxy settings causing this, but
A) I don't know how to verify this
B) If that's the case, how can I tell the client lib to ignore this

client: v12.0
OS: Windows 7
JDK: Oracle 1.7.0_72

**Comment by gschueler** [comment]
i believe that settings tells the proxy selector code to use the "http.proxyHost" and "http.proxyPort" system properties as the proxy.  I think you can bypass that with a list of hosts you don't want to proxy with "http.nonProxyHosts" system property

**Comment by andham** [comment]
I've tried the "http.nonProxyHosts" system property but it doesn't make any difference. :-(

**Comment by gschueler** [comment]
ok, i'm updating the client lib to add newer api (v13) support, I'm also tinkering with the httpclient setup and making the proxy stuff more configurable, as well as removing that java.net.userSystemProxies, since that should be configured by end user when starting jvm

**Comment by andham** [comment]
OK, great! I'm using the rundeck jenkins plugin and the proxy config should be handled by that plugin and not this lib.

If you're going to do a new release I'll send you some PRs for some other minor things that could be improved.

**Comment by gschueler** [comment]
ok, i should merge the api 13 stuff shortly
