### ISSUE TITLE
Unit test errors when building

### ISSUE THREAD

**Issue by andham** [rundeck/rundeck-api-java-client#23]
I'm trying to build and run into unit tests error. I see this on both Mac and Windows. As the Mac is my main dev machine I list that environment:

Apache Maven 3.0.5 (r01de14724cdef164cd33c7c8c2fe155faf9602da; 2013-02-19 14:51:28+0100)
Maven home: /usr/local/maven
Java version: 1.7.0_71, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.7.0_71.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.10.3", arch: "x86_64", family: "mac"

The errors are in RundeckClientTest. Surefire report in this gist:
https://gist.github.com/andham/c4029512e4833836319a

**Comment by gschueler** [comment]
you might try adding to /etc/hosts to point rundeck.local at localhost

i'm also updating use of betamax for testing, I think with java 7 we can change from "rundeck.local" to just specify "localhost" for tests

**Comment by andham** [comment]
Justed tested latest on master, which seems to include the fixes you talk about, and the unit tests now work fine (on a Windows machine).
